[package]
name = "wizardry-kod-util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bitflags = "2.6.0"
byteorder = "1.5.0"
clap = { version = "4.5.19", features = ["derive"] }
itertools = "0.13.0"
num_enum = "0.7.3"
