pub const SPELL_COUNT: usize = 53;

/// 指定したIDの呪文名を返す。
pub fn spell_name(id: usize) -> &'static str {
    const TABLE: [&str; SPELL_COUNT] = [
        "Halito",
        "Mogref",
        "Katino",
        "Dumapic",
        "Dilto",
        "Sopic",
        "Melito",
        "Mahalito",
        "Molito",
        "Morlis",
        "Tzalik",
        "Dalto",
        "Lahalito",
        "Mamorlis",
        "Makanito",
        "Madalto",
        "Zilwan",
        "Lakanito",
        "Masopic",
        "Haman",
        "Ladalto",
        "Malor",
        "Mahaman",
        "Tiltowait",
        "Kalki",
        "Dios",
        "Badios",
        "Milwa",
        "Porfic",
        "Matu",
        "Calfo",
        "Manifo",
        "Montino",
        "Kandi",
        "Dial",
        "Badial",
        "Dialko",
        "Latumapic",
        "Lomilwa",
        "Litokan",
        "Bamatu",
        "Latumofis",
        "Maporfic",
        "Dialma",
        "Badialma",
        "Di",
        "Badi",
        "Lorto",
        "Madi",
        "Mabadi",
        "Loktofeit",
        "Malikto",
        "Kadorto",
    ];

    TABLE[id]
}
